### ISSUE TITLE
UVに対して貼られている画像を抜きたい

### ISSUE THREAD

**Issue by m-sigepon** [devil-tamachan/MQDrawPolygon#1]
メタセコで、UVで貼っている画像を抜くのに対応できないでしょうか。
クリップボードの画像に対して処理を行っているようなので、すでに作ってあるオブジェクトに対して形状のアルファを作成してそれをポリゴンで抜くというのができればと思います。

**Comment by devil-tamachan** [comment]
多分できると思います。
ただ他のプラグイン作っているのでその後になります

**Comment by m-sigepon** [comment]
対応していただけるだけ御の字なので、全然だいじょうぶです！

**Comment by devil-tamachan** [comment]
1.2で対応しました

**Comment by m-sigepon** [comment]
ありがとうございます！
